### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mxg007** [PaParaZz1/PointNet#1]
Dear friends:
When I run show_cls.py，there is an error：

F:\anaconda1\python.exe C:/Users/123456/Desktop/PointNet/pointnet_pytorch-master_lingzhang1/show_cls1.py
Namespace(model='', num_points=2500)
{'Airplane': 0, 'Bag': 1, 'Cap': 2, 'Car': 3, 'Chair': 4, 'Earphone': 5, 'Guitar': 6, 'Knife': 7, 'Lamp': 8, 'Laptop': 9, 'Motorbike': 10, 'Mug': 11, 'Pistol': 12, 'Rocket': 13, 'Skateboard': 14, 'Table': 15}
Traceback (most recent call last):
  File "C:/Users/123456/Desktop/PointNet/pointnet_pytorch-master_lingzhang1/show_cls1.py", line 31, in <module>
    classifier.load_state_dict(torch.load(opt.model))
  File "F:\anaconda1\lib\site-packages\torch\serialization.py", line 301, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by PaParaZz1** [comment]
You need to train this model yourself and save your own model weights. I didn't upload the pre-trained model weight.

**Comment by mxg007** [comment]
teacher:
When I run show_cls.py
i:1  loss: 2.079445 accuracy: 0.031250
i:2  loss: 2.079467 accuracy: 0.000000
i:3  loss: 2.079436 accuracy: 0.062500
i:4  loss: 2.079478 accuracy: 0.000000
i:5  loss: 2.079460 accuracy: 0.000000
i:6  loss: 2.079444 accuracy: 0.000000
i:7  loss: 2.079463 accuracy: 0.000000
i:8  loss: 2.079488 accuracy: 0.000000
i:9  loss: 2.079418 accuracy: 0.062500
i:10  loss: 2.079412 accuracy: 0.031250
"""

"""
why is  that？

**Comment by mxg007** [comment]
thanks,I make it
